spring.application.name=animalkingdom
spring.datasource.url=jdbc:mysql://localhost:3306/animalKingdomDB
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update